[project]
name = "geometry-lib"
version = "0.1.0"
description = "Библиотека для вычисления площадей геометрических фигур"
authors = [{ name = "Роман Комоско" }]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
